# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa66e50b8ae1c5da0e23a5226d9b1d3877e0bd01c2515b0162f09755e093bb3b4c9791195472952343faafd4a5cb6c93bf150032ea80f9c74a64b0cbc17302e8

test:
  secret_key_base: 9621902f2edb292189b1d142a6183b64663bd77233101d38a11b9d7933abc62e4909fbb002810a6995dbc35237e80b484595b38166e076c6963faff5a7dcc971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
